# Generated by Django 5.0.3 on 2024-03-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики'},
        ),
    ]
