# Generated by Django 5.0.3 on 2024-03-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_is_main_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main'], 'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики'},
        ),
    ]
