# Generated by Django 5.0.3 on 2024-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_studentteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteachers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
