# Generated by Django 5.0.3 on 2024-03-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_studentteachers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentteachers',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentteachers',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
