# Generated by Django 5.0.3 on 2024-03-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_student_id_studentteachers_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeachers',
        ),
    ]
